#!/bin/sh
# spec.sh - run examples/ and tests/cases/ through the real binary.
#
#   bash tests/spec.sh            # full check when build/vxa.exe links
#   bash tests/spec.sh --parse    # force the parse-only tier
#
# Two tiers:
#   T1 parse  - always available: lex() + parse_program() over every file, and the
#               "# expect:" header is checked against what the parser actually did.
#   T2 run    - needs build/vxa.exe: each case is run and its exit code / error
#               code is compared with the header. Exits are asserted, not eyeballed.
#
# If the binary cannot be produced yet, T2 prints "SKIP: binary missing" plus what
# it would have checked, and the script still exits 0. That is the state of this
# tree while src/*.c is mid-flight: the grammar is testable, the runtime is not.
set -u
cd "$(dirname "$0")/.." || exit 1

CC=${CC:-/c/msys64/mingw64/bin/cc.exe}
[ -x "$CC" ] || CC=cc
# cc.exe needs its own bin dir on PATH for libgcc/isl DLLs or it exits 1 silently.
case "$CC" in */*) export PATH="$(dirname "$CC"):$PATH" ;; esac
mkdir -p build

BIN=build/vxa.exe
DRIVER=build/spec_parse.c
EXE=build/spec_parse.exe
parse_only=0
[ "${1:-}" = "--parse" ] && parse_only=1

pass=0 fail=0 skip=0
ok()   { pass=$((pass+1)); printf '  ok    %-34s %s\n' "$1" "$2"; }
bad()  { fail=$((fail+1)); printf '  FAIL  %-34s %s\n' "$1" "$2"; }
skip() { skip=$((skip+1)); printf '  SKIP  %-34s %s\n' "$1" "$2"; }

# ---------- T1: parse tier ----------
build_driver() {
  cat > "$DRIVER" <<'EOF'
/* generated by tests/spec.sh - reports what lex()+parse_program() did with a file.
 * lines: "<path>\tOK|-", "<path>\tERR\t<file>:<line>:<col>: msg", "<path>\tLEX\tlex:<line>:<col>: msg" */
#include "ast.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static Arena A;
int main(int argc, char **argv) {
  arena_init(&A, 0);
  for (int i = 1; i < argc; i++) {
    FILE *f = fopen(argv[i], "rb");
    if (!f) { printf("%s\tERR\t%s:1:1: cannot read file\n", argv[i], argv[i]); continue; }
    fseek(f, 0, SEEK_END); long n = ftell(f); fseek(f, 0, SEEK_SET);
    char *buf = (char*)malloc((size_t)n + 1);
    size_t rd = fread(buf, 1, (size_t)n, f); fclose(f);
    buf[rd] = 0;
    Lexer lx; memset(&lx, 0, sizeof lx); lx.a = &A;
    lex(&A, buf, rd, &lx);
    if (lx.err) { printf("%s\tLEX\t%s\n", argv[i], lx.err); continue; }
    char *err = NULL; int el = 0;
    Node *r = parse_program(&A, lx.toks, lx.n, argv[i], &err, &el);
    if (!r) printf("%s\tERR\t%s\n", argv[i], err ? err : "no error text");
    else printf("%s\tOK\t-\n", argv[i]);
  }
  return 0;
}
EOF
  $CC -std=c17 -O2 -g0 -w -Isrc -D_GNU_SOURCE -o "$EXE" "$DRIVER" tests/stubs.c \
      src/util.c src/val.c src/lex.c src/parse.c -lm > build/spec_parse.log 2>&1
}

[ -f tests/stubs.c ] || { echo "spec: tests/stubs.c missing - cannot link the parse harness"; exit 1; }
if [ ! -x "$EXE" ] || [ src/parse.c -nt "$EXE" ] || [ src/lex.c -nt "$EXE" ]; then
  build_driver || { echo "spec: COMPILE-FAIL parse harness"; sed -n '1,15p' build/spec_parse.log; exit 1; }
fi

cases=$(ls tests/cases/*.vxa 2>/dev/null)
examples=$(ls examples/*.vxa 2>/dev/null)
[ -n "$cases$examples" ] || { echo "spec: nothing to check"; exit 1; }

report=$(mktemp) || exit 1
"$EXE" $cases $examples > "$report" 2>&1 || { echo "spec: harness crashed"; exit 1; }

expect_of() { sed -n '1,4p' "$1" | tr -d '\r' | sed -n 's/^# expect: //p' | head -1; }
# the position the parser blamed: first "path:line:col:" field of the message
line_of() { printf '%s' "$1" | sed -n 's/.*[:\\/]\([0-9][0-9]*\):[0-9][0-9]*:.*/\1/p'; }

echo "T1 parse tier (lex + parse_program over every program in the tree)"
for f in $cases; do
  b=$(basename "$f")
  row=$(printf '%s\t' "$f"; printf '' )
  kind=$(awk -F'\t' -v p="$f" '$1==p{print $2; exit}' "$report")
  msg=$(awk -F'\t' -v p="$f" '$1==p{print $3; exit}' "$report")
  exp=$(expect_of "$f")
  case "$exp" in
    syntax-error*|lex-error*)
      want=$(echo "$exp" | awk '{print $3}')
      wantkind=ERR; [ "${exp%% *}" = "lex-error" ] && wantkind=LEX
      if [ "$kind" != "$wantkind" ]; then bad "$b" "expected refusal ($exp), got $kind $msg"
      elif [ "$(line_of "$msg")" != "$want" ]; then bad "$b" "refused at the wrong line: $msg (want line $want)"
      else ok "$b" "refused as expected: $msg"; fi ;;
    ok|exit*|OUTSIDE_JAIL|*)
      if [ "$kind" = OK ]; then ok "$b" "parses (behaviour: $exp)"
      else bad "$b" "must parse, got $kind $msg"; fi ;;
  esac
done
for f in $examples; do
  b=$(basename "$f")
  kind=$(awk -F'\t' -v p="$f" '$1==p{print $2; exit}' "$report")
  msg=$(awk -F'\t' -v p="$f" '$1==p{print $3; exit}' "$report")
  if [ "$kind" = OK ]; then ok "$b" "parses"; else bad "$b" "example must parse, got $kind $msg"; fi
done

# ---------- T2: run tier ----------
if [ -x "$BIN" ] && [ "$parse_only" -eq 0 ]; then
  echo
  echo "T2 run tier ($BIN)"
  for f in $cases; do
    b=$(basename "$f"); exp=$(expect_of "$f")
    skipwhy=$(sed -n 's/^# run: skip \(.*\)/\1/p' "$f" | head -1)
    if [ -n "$skipwhy" ]; then skip "$b" "runtime not wired: $skipwhy"; continue; fi
    out=$("$BIN" run "$f" --quiet 2>&1); got=$?
    case "$exp" in
      syntax-error*|lex-error*) want=2; code=SYNTAX ;;
      ok)               want=0; code="" ;;
      exit*)            want=$(echo "$exp" | awk '{print $2}'); code=$(echo "$exp" | awk '{print $3}') ;;
      OUTSIDE_JAIL)     want=4; code=OUTSIDE_JAIL ;;
      *)                want=0; code="" ;;
    esac
    if [ "$got" -ne "$want" ]; then bad "$b" "exit $got want $want :: $(printf '%s' "$out" | head -1)"
    elif [ -n "$code" ] && ! printf '%s' "$out" | grep -q "code=$code"; then
      bad "$b" "no code=$code in: $(printf '%s' "$out" | head -1)"
    else ok "$b" "exit $got${code:+ code=$code}"; fi
  done
  for f in $examples; do
    b=$(basename "$f")
    why=$(sed -n 's/^# run: skip \(.*\)//p' "$f" | head -1)
    if [ -n "$why" ]; then skip "$b" "runtime not wired: $why"; continue; fi
    out=$("$BIN" run "$f" --quiet 2>&1); got=$?
    case "$got" in
      0|3|5) printf '  info  %-34s exit %s (0 done, 3 waiting for a token, 5 io)\n' "$b" "$got" ;;
      *) bad "$b" "unexpected exit $got :: $(printf '%s' "$out" | head -1)" ;;
    esac
  done
else
  echo
  echo "T2 run tier: SKIP: binary missing ($BIN does not link yet)"
  echo "   not verified while this is true:"
  for f in $cases; do
    exp=$(expect_of "$f")
    case "$exp" in exit*|OUTSIDE_JAIL) printf '   - %s: %s\n' "$(basename "$f")" "$exp" ;; esac
  done
  echo "   - every example's confirm round trip (plan -> --confirm TOKEN -> applied/replayed)"
  echo "   - the compact bytes each program actually emits (only the shape was checked above)"
  skip=$((skip+1))
fi

echo
printf 'spec: pass=%d fail=%d skip=%d\n' "$pass" "$fail" "$skip"
rm -f "$report"
[ "$fail" -eq 0 ] || exit 1
exit 0
